version: "2"
services:
  baby_stats_app:
    container_name: baby_stats_app
    restart: always
    build: .
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    links:
      - mongo
  mongo:
    container_name: mongo_db
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
